config/routes.rb
Rails.application.routes.draw do
  resources :urls

  root to: 'urls#index'

  get '/s/:encode_id', to: 'urls#decode'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  after_create :clean_urls

  def clean_urls
    shorter_ulr = bijective_encode(id)
    sanitize_long_url = long_url.downcase.gsub(/(https?:\/\/)|(www\.)/,"")
    self.update(long_url: "http://#{sanitize_long_url}", short_url: "http://localhost:3000/s/#{shorter_ulr}")
  end

  private

  ALPHABET =
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".split(//)

  def bijective_encode(i)
    return ALPHABET[0] if i == 0
    s = ''
    base = ALPHABET.length
    while i > 0
      s << ALPHABET[i.modulo(base)]
      i /= base
    end
    s.reverse
  end

  def self.bijective_decode(s)
    i = 0
    base = ALPHABET.length
    s.each_char { |c| i = i * base + ALPHABET.index(c) }
    i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
    @url = Url.new
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def decode
    url_id = Url.bijective_decode(params[:encode_id])
    url = Url.find(url_id)
    url.update(visits: url.visits+1)
    redirect_to url.long_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def url_params
      params.require(:url).permit(:long_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlueCoding</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_with(model: url) do |form| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :long_url %>
    <%= form.text_field :long_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Urls</h1>

<%= render 'form', url: @url %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Long Url</th>
      <th>Short Url</th>
      <th>Visits</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.title %></td>
        <td><%= url.long_url %></td>
        <td><%= url.short_url %></td>
        <td><%= url.visits %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @url.title %>
</p>

<p>
  <strong> Long Url:</strong>
  <%= @url.long_url %>
</p>

<p>
  <strong>Short Url:</strong>
  <%= @url.short_url %>
</p>

<p>
  <strong>Visits:</strong>
  <%= @url.visits %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>